# Generated by Django 3.2.4 on 2021-07-01 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='command',
            field=models.CharField(default='NULL', max_length=30),
        ),
        migrations.AlterField(
            model_name='command',
            name='option',
            field=models.CharField(max_length=50),
        ),
    ]
