# Generated by Django 3.2.4 on 2021-07-01 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command_page', '0002_auto_20210701_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='command',
            field=models.CharField(default='', max_length=30),
        ),
    ]
